image:
  file: .gitpod.Dockerfile

tasks:
  - name: Futurenet
    init: |
      docker pull stellar/quickstart:soroban-dev@sha256:0993d3350148af6ffeab5dc8f0b835236b28dade6dcae77ff8a09317162f768d
    command: |
      docker run --rm -it \
      --name stellar \
      --platform linux/amd64 \
      -p 8000:8000 \
      stellar/quickstart:soroban-dev@sha256:0993d3350148af6ffeab5dc8f0b835236b28dade6dcae77ff8a09317162f768d \
      --futurenet \
      --enable-soroban-rpc
  - name: "Albedo Signer"
    command: |
      cd ~/.local/_client
      clear
      npm run start
  - name: CLI - Futurenet
    env:
      SOROBAN_RPC_URL: "http://127.0.0.1:8000/soroban/rpc"
      SOROBAN_NETWORK_PASSPHRASE: "Test SDF Future Network ; October 2022"
    command: |
      source ~/.local/bash-hook
      source ~/.local/bash-rpc-prompt
      clear
  - name: CLI - Sandbox
    init: |
      cargo clean
      cargo fetch
      cargo build --target wasm32-unknown-unknown --release -p soroban-hello-world-contract
      cargo test -p soroban-hello-world-contract
    command: |
      gp open README.md
      clear

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - rust-lang.rust-analyzer

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: true
    addBadge: true

ports:
  - name: Futurenet
    port: 8000
    visibility: public
    onOpen: ignore
  - name: Albedo Signer
    port: 3000
    visibility: public
    onOpen: ignore
  - port: 4226
    visibility: private
    onOpen: ignore
